### ISSUE TITLE
Implement manual tracking 'hidden content' settings

### ISSUE THREAD

**Issue by JamesDonnelly** [ApkalluFalls/ui#9]
- [x] Implement filters on Account settings page
- [ ] Show and hide content on lists based on filter selection
- [ ] Update navigation progress bar totals to reflect filter selection
